apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    istio-injection: enabled
---

apiVersion: v1
kind: Service
metadata:
    name: proxy-app
    namespace: non-mesh
spec:
    type: NodePort
    selector:
        app: proxy-app
    ports:
        - port: 80
          targetPort: 8080
          nodePort: 32032
          name: "http"
---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: proxy-app
    namespace: non-mesh
    labels:
        app: proxy-app
spec:
    replicas: 1
    selector:
        matchLabels:
            app: proxy-app
    template:
        metadata:
            labels:
                app: proxy-app
        spec:
            containers:
                - name: echoserver
                  image: proxy-app:auth
                  imagePullPolicy: IfNotPresent
                  ports:
                     - containerPort: 8080

---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "default/*"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: echoserver
  namespace: default
spec:
  hosts:
    - echoserver # short name doesn't work, see: https://istio.io/latest/docs/reference/config/networking/virtual-service/#VirtualService
    - echoserver.default
    - echoserver.default.svc
    - echoserver.default.svc.cluster.local
  http:
    - name: "echoserver"
      route:
        - destination:
            host: echoserver-v1.default.svc.cluster.local
            subset: v1
          weight: 30
        - destination:
            host: echoserver-v2.default.svc.cluster.local
            subset: v2
          weight: 70
---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: echoserver-gateway
  namespace: default
spec:
  hosts:
    - echoserver # short name doesn't work, see: https://istio.io/latest/docs/reference/config/networking/virtual-service/#VirtualService
    - echoserver.default
    - echoserver.default.svc
    - echoserver.default.svc.cluster.local
  gateways:
    - gateway
  http:
    - name: "echoserver"
      route:
        - destination:
            host: echoserver-v1.default.svc.cluster.local
            subset: v1
          weight: 30
        - destination:
            host: echoserver-v2.default.svc.cluster.local
            subset: v2
          weight: 70
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: echoserver-v1
  namespace: default
spec:
  host: echoserver-v1.default.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: "1"
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: echoserver-v2
  namespace: default
spec:
  host: echoserver-v2.default.svc.cluster.local
  subsets:
  - name: v2
    labels:
      version: "2"

