---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    istio-injection: enabled # Включаем инжект сайдкаров Istio для неймспейса

---
# this one is the "fake" service to which end use should address
# it shouldn't have selector because it points to another service in anoter namespace, see: https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: default
spec:
  type: ExternalName
  externalName: istio-ingressgateway.istio-system.svc.cluster.local
  # ports:
  #   - port: 80
  #     nodePort: 32080
  #     targetPort: 80
  #     name: "http"  # Istio требует явного указания протокола при определенных настройках

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-v1
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: echoserver
      version: "1"
  template:
    metadata:
      labels:
        app: echoserver
        version: "1"
        istio-gateway: "true"
    spec:
      containers:
        - name: echoserver
          image: jmalloc/echo-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-v1
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: "http"  # Istio требует явного указания протокола при определенных настройках
  selector:
    app: echoserver
    version: "1"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-v2
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: echoserver
      version: "2"
  template:
    metadata:
      labels:
        app: echoserver
        version: "2"
        istio-gateway: "true"
    spec:
      containers:
        - name: echoserver
          image: jmalloc/echo-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-v2
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: "http"  # Istio требует явного указания протокола при определенных настройках
  selector:
    app: echoserver
    version: "2"
